services:
  - type: worker
    name: crypto-alert-bot
    runtime: python
    repo: https://github.com/anooptmr/crypto-alert-bot
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: 7935117230:AAFF6FrTTXUP30LXWcoOicKf82S2lkEx_5A
        value: your_telegram_bot_token
      - key: 383365285
        value: your_telegram_chat_id
